import { buildQueueTaskEnvelope } from './index.js';
import { nowIso } from './diff.js';
export const defaultDraftTemplate = {
  fields: ['title', 'slug', 'summary', 'tags', 'category', 'status'],
  defaults: {
    status: 'draft',
    tags: [],
    category: 'notes'
  },
  branchPrefix: 'draft/',
  postDir: 'source/_posts'
};

export const firstTestArticleTemplate = {
  title: 'xHalo Blog 测试文章',
  slug: 'xhalo-blog-first-test-post',
  category: 'Test',
  tags: ['xhalo-blog', 'test', 'Cloudflare'],
  summary: 'Cloudflare Pages 完整测试站首篇验证文章。',
  body: [
    '# xHalo Blog 测试文章',
    '',
    '这是一篇用于验证 xhalo-blog-test Cloudflare Pages 完整测试站、GitHub OAuth 管理员登录和 test-only direct publish 流程的文章。',
    '',
    '- Pages 承载博客 HTML、Admin 前端和普通静态资源。',
    '- R2 仅作为媒体和附件资产层，不作为整站托管层。',
    '- 生产写入未被批准。'
  ].join('\n')
};

export function slugifyTitle(input = '') {
  return String(input)
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 80);
}

export function normalizeDraftInput(input = {}) {
  const title = String(input.title || '').trim();
  const slug = String(input.slug || slugifyTitle(title)).trim() || 'untitled-draft';
  const summary = String(input.summary || '').trim();
  const body = String(input.body || '').trim();
  const date = String(input.date || '').trim();
  const updated = String(input.updated || '').trim();
  const status = String(input.status || defaultDraftTemplate.defaults.status).trim();
  
  let categories = [];
  if (Array.isArray(input.categories)) {
    categories = input.categories.map((c) => String(c).trim()).filter(Boolean);
  } else if (input.category) {
    categories = [String(input.category).trim()];
  } else {
    categories = [defaultDraftTemplate.defaults.category];
  }

  const tags = Array.isArray(input.tags)
    ? input.tags.map((tag) => String(tag).trim()).filter(Boolean)
    : [];

  return {
    title,
    slug,
    summary,
    body,
    date,
    updated,
    categories,
    tags,
    status,
    category: categories[0] || defaultDraftTemplate.defaults.category
  };
}

export function buildDraftFrontMatter(input = {}) {
  const draft = normalizeDraftInput(input);
  return {
    title: draft.title,
    date: draft.date || nowIso(),
    updated: draft.updated || nowIso(),
    tags: draft.tags,
    categories: draft.categories,
    summary: draft.summary,
    status: draft.status
  };
}

function serializeFrontMatterValue(value) {
  if (Array.isArray(value)) {
    if (value.length === 0) return '[]';
    return `\n${value.map((item) => `  - ${String(item)}`).join('\n')}`;
  }

  if (typeof value === 'string') {
    if (value.length === 0) return '""';
    if (/^[a-zA-Z0-9._/-]+$/.test(value)) return value;
    return JSON.stringify(value);
  }

  return JSON.stringify(value);
}

export function buildDraftFilePath(input = {}) {
  const draft = normalizeDraftInput(input);
  return `${defaultDraftTemplate.postDir}/${draft.slug}.md`;
}

export function buildDraftMarkdownDocument(input = {}) {
  const draft = normalizeDraftInput(input);
  const frontMatter = buildDraftFrontMatter(draft);
  const frontMatterLines = Object.entries(frontMatter).map(([key, value]) => `${key}: ${serializeFrontMatterValue(value)}`);
  const body = draft.body || draft.summary || 'Draft body placeholder.';

  return `---\n${frontMatterLines.join('\n')}\n---\n\n${body}\n`;
}

export function buildDraftBranchName(input = {}) {
  const draft = normalizeDraftInput(input);
  return `${defaultDraftTemplate.branchPrefix}${draft.slug}`;
}

export function buildPullRequestBody(draft) {
  return [
    `## Summary`,
    ``,
    `Create a draft article for owner review.`,
    ``,
    `## Article`,
    ``,
    `- Title: ${draft.title || ''}`,
    `- Slug: ${draft.slug || ''}`,
    `- Path: source/_posts/${draft.slug || ''}.md`,
    `- Status: ${draft.status || 'draft'}`,
    `- Categories: ${(draft.categories || []).join(', ')}`,
    `- Tags: ${(draft.tags || []).join(', ')}`,
    ``,
    `## Safety`,
    ``,
    `- Direct main write: no`,
    `- Auto-merge: no`,
    `- Owner manual review required: yes`,
    `- Generated by xhalo-blog PR-only publishing pipeline`,
    ``,
    `## Review Checklist`,
    ``,
    `- [ ] Title is correct`,
    `- [ ] Slug is correct`,
    `- [ ] Frontmatter is valid`,
    `- [ ] Content is ready`,
    `- [ ] No secrets or sensitive URLs`,
    `- [ ] Merge manually or close without merge`,
    ``,
    `## Notes`,
    ``,
    `This PR does not publish content until the repository owner manually merges it.`
  ].join('\n');
}

export function buildPullRequestPreview(input = {}, options = {}) {
  const draft = normalizeDraftInput(input);
  const branchName = buildDraftBranchName(draft);
  const filePath = buildDraftFilePath(draft);
  const repoOwner = options.repoOwner || 'example';
  const repoName = options.repoName || 'xhalo-blog';
  const baseBranch = options.baseBranch || 'main';
  const pullRequestBody = buildPullRequestBody(draft);

  return {
    draft,
    branchName,
    baseBranch,
    filePath,
    frontMatter: buildDraftFrontMatter(draft),
    commitMessage: `feat(posts): add draft ${draft.slug}`,
    pullRequestTitle: `Add draft: ${draft.title || draft.slug}`,
    pullRequestBody,
    repository: `${repoOwner}/${repoName}`
  };
}

export function buildDraftTaskPrototype(input = {}, options = {}) {
  const preview = buildPullRequestPreview(input, options);
  const createdAt = nowIso();
  const task = buildQueueTaskEnvelope({
    type: 'draft_preview',
    stage: options.stage || '3-prototype',
    created_at: createdAt,
    idempotency_key: crypto.randomUUID(),
    preview
  });

  return {
    preview,
    queuedTask: task,
    taskRecord: {
      id: task.idempotency_key,
      type: task.type,
      status: 'queued',
      payload: task,
      created_at: createdAt,
      updated_at: createdAt
    }
  };
}

export function buildDraftPublishTaskPrototype(input = {}, options = {}) {
  const preview = buildPullRequestPreview(input, options);
  const createdAt = nowIso();
  const task = buildQueueTaskEnvelope({
    type: 'draft_publish',
    stage: options.stage || '4-release-candidate',
    created_at: createdAt,
    idempotency_key: crypto.randomUUID(),
    publish_target: input.publish_target || null,
    preview
  });

  return {
    preview,
    queuedTask: task,
    taskRecord: {
      id: task.idempotency_key,
      type: task.type,
      status: 'queued',
      payload: task,
      created_at: createdAt,
      updated_at: createdAt
    }
  };
}


export function buildGitHubWritePlan(input = {}, options = {}) {
  const preview = buildPullRequestPreview(input, options);

  return {
    repository: preview.repository,
    branchName: preview.branchName,
    baseBranch: preview.baseBranch,
    filePath: preview.filePath,
    actions: [
      {
        type: 'create_branch',
        summary: `Create ${preview.branchName} from ${preview.baseBranch}`,
        payload: {
          repository: preview.repository,
          baseBranch: preview.baseBranch,
          branchName: preview.branchName
        }
      },
      {
        type: 'write_post_file',
        summary: `Write ${preview.filePath} with generated front matter`,
        payload: {
          filePath: preview.filePath,
          frontMatter: preview.frontMatter
        }
      },
      {
        type: 'commit_changes',
        summary: `Commit draft changes with "${preview.commitMessage}"`,
        payload: {
          commitMessage: preview.commitMessage
        }
      },
      {
        type: 'open_pull_request',
        summary: `Open PR "${preview.pullRequestTitle}" into ${preview.baseBranch}`,
        payload: {
          repository: preview.repository,
          title: preview.pullRequestTitle,
          baseBranch: preview.baseBranch,
          headBranch: preview.branchName
        }
      },
      {
        type: 'verify_preview_deployment',
        summary: 'Wait for the preview deployment and validate the draft URL before merge',
        payload: {
          provider: 'cloudflare-pages',
          branchName: preview.branchName
        }
      }
    ]
  };
}

export function validateDraftSlug(slug) {
  const errors = [];
  if (slug === undefined || slug === null) {
    errors.push('Missing required field: slug');
    return errors;
  }
  
  const slugStr = String(slug).trim();
  if (slugStr.length === 0) {
    errors.push('slug cannot be empty');
  } else if (slugStr.length > 100) {
    errors.push('slug cannot be longer than 100 characters');
  }
  
  if (/[A-Z]/.test(slugStr) || /_/.test(slugStr) || !/^[a-z0-9-]+$/.test(slugStr) || slugStr.startsWith('-') || slugStr.endsWith('-')) {
    errors.push('slug contains invalid characters. Only lowercase alphanumeric and hyphens are allowed.');
  }

  // Path traversal check inside slug
  if (slugStr.includes('..') || slugStr.includes('/') || slugStr.includes('\\') || slugStr.includes(':')) {
    errors.push('Path traversal or absolute path is not allowed');
  }

  return errors;
}

export function validateDraftPath(input) {
  const errors = [];
  if (!input || typeof input !== 'object') {
    errors.push('Input must be an object');
    return errors;
  }

  const slug = String(input.slug || '').trim();
  const targetPath = `source/_posts/${slug}.md`;

  if (targetPath.includes('..') || targetPath.includes('\\') || targetPath.startsWith('/') || targetPath.includes(':')) {
    errors.push('Path traversal or absolute path is not allowed');
  }

  if (!targetPath.startsWith('source/_posts/')) {
    errors.push('Target path must remain strictly under source/_posts/');
  }

  return errors;
}

export function validateDraftInput(input) {
  const errors = [];
  if (!input || typeof input !== 'object') {
    errors.push('Request body must be a JSON object');
    return errors;
  }

  // Title validation
  if (input.title === undefined || input.title === null) {
    errors.push('Missing required field: title');
  } else {
    const title = String(input.title).trim();
    if (title.length === 0) {
      errors.push('title cannot be empty');
    } else if (title.length > 200) {
      errors.push('title cannot be longer than 200 characters');
    }
  }

  // Slug & Path validation
  if (input.slug === undefined || input.slug === null) {
    errors.push('Missing required field: slug');
  } else {
    const slugErrors = validateDraftSlug(input.slug);
    errors.push(...slugErrors);
    if (slugErrors.length === 0) {
      errors.push(...validateDraftPath(input));
    }
  }

  // Status validation
  if (input.status !== undefined && input.status !== null) {
    const status = String(input.status).trim();
    if (status !== 'draft' && status !== 'review' && status !== 'published') {
      errors.push('status must be either "draft", "review" or "published"');
    }
  }

  // Mode validation
  if (input.mode !== undefined && input.mode !== null) {
    const mode = String(input.mode).trim();
    if (mode !== 'dry-run' && mode !== 'live') {
      errors.push('mode must be either "dry-run" or "live"');
    }
  }

  // Publish target validation
  if (input.publish_target !== undefined && input.publish_target !== null) {
    const publishTarget = String(input.publish_target).trim();
    if (publishTarget !== 'github' && publishTarget !== 'd1') {
      errors.push('publish_target must be either "github" or "d1"');
    }
  }

  // Summary validation
  if (input.summary !== undefined && input.summary !== null) {
    if (typeof input.summary !== 'string') {
      errors.push('summary must be a string');
    } else {
      const summary = input.summary.trim();
      if (summary.length > 500) {
        errors.push('summary cannot be longer than 500 characters');
      }
    }
  }

  // Category & Categories validation
  if (input.categories !== undefined && input.categories !== null) {
    if (!Array.isArray(input.categories)) {
      errors.push('categories must be an array of strings');
    } else {
      for (let index = 0; index < input.categories.length; index += 1) {
        const cat = input.categories[index];
        if (typeof cat !== 'string') {
          errors.push(`categories at index ${index} must be a string`);
        } else if (cat.trim().length > 100) {
          errors.push(`category "${cat.slice(0, 10)}..." cannot be longer than 100 characters`);
        }
      }
    }
  } else if (input.category !== undefined && input.category !== null) {
    if (typeof input.category !== 'string') {
      errors.push('category must be a string');
    } else {
      const category = input.category.trim();
      if (category.length > 100) {
        errors.push('category cannot be longer than 100 characters');
      }
    }
  }

  // Content/Body validation (body is required)
  if (input.body === undefined || input.body === null) {
    errors.push('Missing required field: body');
  } else if (typeof input.body !== 'string') {
    errors.push('body must be a string');
  } else {
    const bodyBytes = new TextEncoder().encode(input.body).byteLength;
    if (bodyBytes > 200 * 1024) {
      errors.push('body content size cannot exceed 200 KiB');
    }
  }

  // Tags validation
  if (input.tags !== undefined && input.tags !== null) {
    let parsedTags = [];
    if (Array.isArray(input.tags)) {
      for (let index = 0; index < input.tags.length; index += 1) {
        const tag = input.tags[index];
        if (typeof tag !== 'string') {
          errors.push(`tags at index ${index} must be a string`);
        } else {
          parsedTags.push(tag.trim());
        }
      }
    } else if (typeof input.tags === 'string') {
      parsedTags = input.tags.split(',').map((t) => t.trim()).filter(Boolean);
    } else {
      errors.push('tags must be a string or an array of strings');
    }

    if (parsedTags.length > 20) {
      errors.push('tags list cannot contain more than 20 items');
    }
    for (const tag of parsedTags) {
      if (tag.length > 50) {
        errors.push(`tag "${tag.slice(0, 10)}..." cannot be longer than 50 characters`);
      }
    }
  }

  return errors;
}
