import { apiFetch } from './api-client.js';
import { getLanguage, isZh } from './i18n.js';
import { escapeHtml, showToast } from './ui.js';

export const FIRST_TEST_ARTICLE_TEMPLATE = {
  title: 'xHalo Blog 测试文章',
  slug: 'xhalo-blog-first-test-post',
  category: 'Test',
  tags: 'xhalo-blog, test, Cloudflare',
  body: [
    '# xHalo Blog 测试文章',
    '',
    '这是一篇用于验证 xhalo-blog-test Cloudflare Pages、GitHub OAuth 管理员登录和 test-only direct publish 流程的文章。',
    '',
    '- Pages 承载博客 HTML、Admin 前端和普通静态资源。',
    '- R2 仅作为媒体和附件资产层，不作为整站托管层。',
    '- 生产写入未被批准。'
  ].join('\n'),
  filePath: ''
};

const EMPTY_POST = {
  title: '',
  slug: '',
  category: '',
  tags: '',
  body: '',
  sha: '',
  filePath: ''
};

const MEDIA_SNIPPETS = [
  { id: 'image', zh: '图片', en: 'Image', snippet: '\n![image alt](media/example-image.png)\n' },
  { id: 'document', zh: '文档', en: 'Document', snippet: '\n[document.pdf](media/document.pdf)\n' },
  { id: 'audio', zh: '音频', en: 'Audio', snippet: '\n<audio controls src="media/audio.mp3"></audio>\n' },
  { id: 'video', zh: '视频', en: 'Video', snippet: '\n<video controls src="media/video.mp4"></video>\n' },
  { id: 'attachment', zh: '附件', en: 'Attachment', snippet: '\n[download attachment](media/attachment.zip)\n' }
];

const copy = {
  zh: {
    title: '文章编辑器',
    template: '使用测试模板',
    blank: '空白草稿',
    loadSource: '加载 main 源码',
    notice: '发布到测试站会优先更新当前文章真实路径 {path}，写入后触发 Pages 构建。Hexo 首页以 frontmatter 标题、摘要和 permalink 规则生成。',
    edit: '编辑',
    diff: 'Diff',
    plan: 'PR 计划',
    titleField: '文章标题',
    slug: '文章 Slug',
    category: '分类',
    tags: '标签（逗号分隔）',
    sourcePath: '源文件路径',
    body: '正文内容（Vditor Markdown）',
    media: '插入媒体附件',
    mediaShortcuts: '快速插入媒体标签',
    previewDiff: '预览 Diff',
    dryRun: 'Dry-run PR 计划',
    createPr: '创建审核 PR',
    publishTest: '发布到测试站',
    prUnavailable: '创建审核 PR 暂不可用：LIVE_WRITES_ENABLED=false',
    publishUnavailable: '发布到测试站暂不可用',
    fillSlug: '请先填写 Slug。',
    sourceLoaded: '源码加载成功',
    sourceFailed: '源码加载失败',
    diffReady: 'Diff 生成成功',
    diffFailed: 'Diff 生成失败',
    planReady: '发布计划已生成',
    planFailed: '获取计划失败',
    blocked: '操作被写入 gate 阻断',
    dispatched: 'PR 创建任务已派发',
    operationFailed: '操作失败',
    published: '已发布到测试目标',
    publishFailed: '测试发布失败',
    insertMedia: '已插入媒体 Markdown 标签，请在媒体管理页生成真实链接后替换路径。',
    emptyDiff: '生成 Diff 后查看变更细节。',
    emptyPlan: '生成发布计划后预览操作。',
    vditorPlaceholder: '使用 Markdown 编写正文，支持粘贴、拖拽、表格、代码块、表情和媒体链接...',
    stats: '行数 {lines} · 字符 {chars} · Words {words}',
    pagesTriggered: 'Pages build triggered',
    pagesNotTriggered: 'Pages build not triggered'
  },
  en: {
    title: 'Article Editor',
    template: 'Use Test Template',
    blank: 'Blank Draft',
    loadSource: 'Load Main Source',
    notice: 'Publish to Test updates the real source path {path} first and triggers a Pages build after the write. Hexo homepage output follows frontmatter title, summary, and permalink rules.',
    edit: 'Edit',
    diff: 'Diff',
    plan: 'PR Plan',
    titleField: 'Article Title',
    slug: 'Article Slug',
    category: 'Category',
    tags: 'Tags (comma separated)',
    sourcePath: 'Source File Path',
    body: 'Body Content (Vditor Markdown)',
    media: 'Insert Media',
    mediaShortcuts: 'Quick Media Tags',
    previewDiff: 'Preview Diff',
    dryRun: 'Dry-run PR Plan',
    createPr: 'Create Review PR',
    publishTest: 'Publish to Test',
    prUnavailable: 'Create Review PR unavailable: LIVE_WRITES_ENABLED=false',
    publishUnavailable: 'Publish to Test unavailable',
    fillSlug: 'Please fill out the Slug field first.',
    sourceLoaded: 'Source loaded successfully',
    sourceFailed: 'Failed to load source',
    diffReady: 'Diff generated successfully',
    diffFailed: 'Failed to generate diff',
    planReady: 'Publish plan computed',
    planFailed: 'Failed to retrieve plan',
    blocked: 'Action blocked by write gate',
    dispatched: 'PR creation task dispatched',
    operationFailed: 'Operation failed',
    published: 'Published to test target',
    publishFailed: 'Test publish failed',
    insertMedia: 'Inserted a media Markdown tag. Replace it with a real link generated by Media Manager.',
    emptyDiff: 'Generate a diff to inspect change details.',
    emptyPlan: 'Generate a publish plan to preview operations.',
    vditorPlaceholder: 'Write Markdown with paste, drag-drop, tables, code blocks, emoji, and media links...',
    stats: 'Lines {lines} · Characters {chars} · Words {words}',
    pagesTriggered: 'Pages build triggered',
    pagesNotTriggered: 'Pages build not triggered'
  }
};

let vditorAssetsPromise = null;

function c(key) {
  return (isZh() ? copy.zh : copy.en)[key];
}

function interpolate(template, params) {
  return Object.entries(params).reduce((value, [key, replacement]) => value.replaceAll(`{${key}}`, String(replacement)), template);
}

export async function fetchPostSource(slug, targetPath = '') {
  const query = new URLSearchParams({ slug });
  if (targetPath) query.set('targetPath', targetPath);
  const res = await apiFetch(`/api/posts/source?${query.toString()}`);
  if (!res.ok) throw new Error(`Source API returned status ${res.status}`);
  return await res.json();
}

function ensureVditorAssets() {
  if (window.Vditor) return Promise.resolve(window.Vditor);
  if (vditorAssetsPromise) return vditorAssetsPromise;
  vditorAssetsPromise = new Promise((resolve, reject) => {
    const css = document.createElement('link');
    css.rel = 'stylesheet';
    css.href = 'https://unpkg.com/vditor/dist/index.css';
    document.head.appendChild(css);

    const script = document.createElement('script');
    script.src = 'https://unpkg.com/vditor/dist/index.min.js';
    script.async = true;
    script.onload = () => resolve(window.Vditor);
    script.onerror = () => reject(new Error('Vditor failed to load.'));
    document.head.appendChild(script);
  });
  return vditorAssetsPromise;
}

export function renderEditor(container, { initialPost, dashboardData }) {
  let post = normalizePost(initialPost || { ...FIRST_TEST_ARTICLE_TEMPLATE, sha: '' });
  let activeTab = 'edit';
  let diffHtml = '';
  let planHtml = '';
  let actionResultHtml = '';
  let loadingState = false;
  let autoLoadAttempted = false;

  const readiness = dashboardData?.readiness || {};
  const isTestDirectPublishEnabled = readiness.deploymentEnv === 'test' &&
    readiness.publishMode === 'test_direct' &&
    readiness.testDirectPublishEnabled === true &&
    readiness.testDirectTargetSafe === true;

  const testPublishDisabledReason = readiness.deploymentEnv !== 'test'
    ? 'DEPLOYMENT_ENV must be test'
    : readiness.publishMode !== 'test_direct'
      ? 'PUBLISH_MODE must be test_direct'
      : readiness.testDirectPublishEnabled !== true
        ? 'TEST_DIRECT_PUBLISH_ENABLED must be true'
        : readiness.testDirectTargetSafe !== true
          ? 'Target repository/branch is not test-safe'
          : '';

  function syncFromForm() {
    const getValue = (id) => container.querySelector(id)?.value || '';
    const vditor = container.querySelector('#vditor-editor')?._xhaloVditor;
    post = {
      ...post,
      title: getValue('#edit-title'),
      slug: getValue('#edit-slug'),
      category: getValue('#edit-category'),
      tags: getValue('#edit-tags'),
      body: vditor ? vditor.getValue() : getValue('#edit-body'),
      filePath: getValue('#edit-file-path')
    };
  }

  async function loadExistingSource() {
    if (!post.slug) return;
    loadingState = true;
    draw();
    try {
      const data = await fetchPostSource(post.slug, post.filePath);
      post = normalizePost({
        title: data.frontmatter?.title || post.title || '',
        slug: post.slug,
        category: data.frontmatter?.category || (Array.isArray(data.frontmatter?.categories) ? data.frontmatter.categories.join(', ') : data.frontmatter?.categories || ''),
        tags: Array.isArray(data.frontmatter?.tags) ? data.frontmatter.tags.join(', ') : '',
        body: data.body || '',
        sha: data.sha || '',
        filePath: data.targetPath || post.filePath || ''
      });
      actionResultHtml = `<div class="alert alert-success">${escapeHtml(c('sourceLoaded'))} (SHA: <code>${escapeHtml(post.sha.substring(0, 7))}</code>)</div>`;
      showToast(c('sourceLoaded'), 'success');
    } catch (err) {
      actionResultHtml = `<div class="alert alert-error">${escapeHtml(c('sourceFailed'))}: ${escapeHtml(err.message)}</div>`;
      showToast(`${c('sourceFailed')}: ${err.message}`, 'error');
    } finally {
      loadingState = false;
      draw();
    }
  }

  async function fetchDiffPreview() {
    syncFromForm();
    if (!post.slug) {
      showToast(c('fillSlug'), 'warning');
      return;
    }
    loadingState = true;
    activeTab = 'diff';
    draw();
    try {
      const res = await apiFetch('/api/drafts/direct-update-preview', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(buildPayload())
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || 'Diff failed');
      const diff = data.diff || {};
      diffHtml = `
        <div class="diff-container">
          <p>Comparing local draft changes against <code>${escapeHtml(diff.filePath || post.filePath || '')}</code>.</p>
          <div class="diff-meta">
            <span>Base SHA: <code>${escapeHtml(diff.baseSha ? diff.baseSha.substring(0, 7) : 'None')}</code></span>
            <span>Status: <strong>${escapeHtml(diff.status || 'modified')}</strong></span>
          </div>
          <div class="diff-code-view">
            <pre class="diff-diff">${escapeHtml(diff.diffText || 'No modifications detected.')}</pre>
          </div>
        </div>
      `;
      showToast(c('diffReady'), 'success');
    } catch (err) {
      diffHtml = `<div class="alert alert-error">${escapeHtml(c('diffFailed'))}: ${escapeHtml(err.message)}</div>`;
      showToast(`${c('diffFailed')}: ${err.message}`, 'error');
    } finally {
      loadingState = false;
      draw();
    }
  }

  async function fetchPublishPlan() {
    syncFromForm();
    loadingState = true;
    activeTab = 'plan';
    draw();
    try {
      const res = await apiFetch('/api/drafts/publish', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ ...buildPayload(), mode: 'dry-run', publish_target: 'github' })
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || 'Plan failed');
      const actions = data.plan?.actions || data.plan?.ops || [];
      planHtml = `
        <div class="plan-container">
          <p><strong>Dry-run Plan Summary:</strong> no remote changes are created.</p>
          <div class="plan-actions-list">
            ${actions.map((act, index) => `
              <div class="plan-step">
                <span class="step-num">Step ${index + 1}</span>
                <div class="step-details">
                  <strong>${escapeHtml(act.op || act.action || 'operation')}</strong>
                  <span>${escapeHtml(act.branch || act.path || act.title || '')}</span>
                </div>
              </div>
            `).join('')}
          </div>
        </div>
      `;
      showToast(c('planReady'), 'success');
    } catch (err) {
      planHtml = `<div class="alert alert-error">${escapeHtml(c('planFailed'))}: ${escapeHtml(err.message)}</div>`;
      showToast(`${c('planFailed')}: ${err.message}`, 'error');
    } finally {
      loadingState = false;
      draw();
    }
  }

  async function handleCreatePR() {
    syncFromForm();
    loadingState = true;
    draw();
    try {
      const res = await apiFetch('/api/drafts/publish', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ ...buildPayload(), mode: 'live', publish_target: 'github' })
      });
      const data = await res.json();
      if (res.status === 403) {
        actionResultHtml = `<div class="alert alert-warning"><strong>${escapeHtml(c('blocked'))}:</strong> <code>${escapeHtml(data.error || 'Live writes are disabled')}</code></div>`;
        showToast(c('blocked'), 'warning');
      } else if (res.ok) {
        actionResultHtml = `<div class="alert alert-success"><strong>${escapeHtml(c('dispatched'))}:</strong> Task ID: <code>${escapeHtml(data.task_id || '')}</code></div>`;
        showToast(c('dispatched'), 'success');
      } else {
        throw new Error(data.error || 'Unexpected error');
      }
    } catch (err) {
      actionResultHtml = `<div class="alert alert-error">${escapeHtml(c('operationFailed'))}: ${escapeHtml(err.message)}</div>`;
      showToast(`${c('operationFailed')}: ${err.message}`, 'error');
    } finally {
      loadingState = false;
      draw();
    }
  }

  async function handlePublishToTest() {
    syncFromForm();
    loadingState = true;
    draw();
    try {
      const res = await apiFetch('/api/drafts/test-direct-publish', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(buildPayload())
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || data.code || 'Test publish failed');
      actionResultHtml = `
        <div class="alert alert-success">
          <strong>${escapeHtml(c('published'))}:</strong>
          <code>${escapeHtml(data.targetRepo || '')}@${escapeHtml(data.targetBranch || '')}</code><br/>
          Path: <code>${escapeHtml(data.targetPath || '')}</code>
          ${data.commitSha ? `<br/>Commit: <code>${escapeHtml(data.commitSha.substring(0, 12))}</code>` : ''}
          ${data.postUrl ? `<br/>Post URL: <a href="${escapeHtml(data.postUrl)}" target="_blank" rel="noreferrer">${escapeHtml(data.postUrl)}</a>` : ''}
          ${data.pagesDeploy?.triggered ? `<br/><span class="status-badge" data-state="ok">${escapeHtml(c('pagesTriggered'))}</span>` : `<br/><span class="status-badge" data-state="warning">${escapeHtml(c('pagesNotTriggered'))}</span>`}
          ${data.pagesDeploy?.deploymentId ? `<br/>Deployment: <code>${escapeHtml(data.pagesDeploy.deploymentId)}</code>` : ''}
          ${data.pagesDeploy?.deploymentUrl ? `<br/>Preview: <a href="${escapeHtml(data.pagesDeploy.deploymentUrl)}" target="_blank" rel="noreferrer">${escapeHtml(data.pagesDeploy.deploymentUrl)}</a>` : ''}
          ${data.pagesDeploy?.error ? `<br/><span class="text-danger">Deploy hook error: ${escapeHtml(data.pagesDeploy.error)}</span>` : ''}
        </div>
      `;
      showToast(c('published'), 'success');
    } catch (err) {
      actionResultHtml = `<div class="alert alert-error">${escapeHtml(c('publishFailed'))}: ${escapeHtml(err.message)}</div>`;
      showToast(`${c('publishFailed')}: ${err.message}`, 'error');
    } finally {
      loadingState = false;
      draw();
    }
  }

  function buildPayload() {
    return {
      title: post.title,
      slug: post.slug,
      category: post.category,
      tags: post.tags ? post.tags.split(',').map((tag) => tag.trim()).filter(Boolean) : [],
      body: post.body,
      targetPath: post.filePath || undefined
    };
  }

  function useTemplate(templateName) {
    post = normalizePost(templateName === 'first-test'
      ? { ...FIRST_TEST_ARTICLE_TEMPLATE, sha: '' }
      : { ...EMPTY_POST });
    activeTab = 'edit';
    actionResultHtml = '';
    draw();
  }

  function draw() {
    container.innerHTML = `
      <div class="editor-workspace">
        <div class="editor-top-actions">
          <h2>${escapeHtml(c('title'))}</h2>
          <div class="source-loader-block">
            <button class="button-small button-secondary" id="btn-template-first">${escapeHtml(c('template'))}</button>
            <button class="button-small button-secondary" id="btn-template-empty">${escapeHtml(c('blank'))}</button>
            <button class="button-small button-secondary" id="btn-load-source" ${post.slug ? '' : 'disabled'}>${escapeHtml(c('loadSource'))}</button>
          </div>
        </div>

        <div class="alert alert-info">
          ${escapeHtml(interpolate(c('notice'), { path: post.filePath || `source/_posts/${post.slug || 'slug'}.md` }))}
        </div>

        <div class="editor-tabs">
          <button class="tab-btn ${activeTab === 'edit' ? 'active' : ''}" data-tab="edit">${escapeHtml(c('edit'))}</button>
          <button class="tab-btn ${activeTab === 'diff' ? 'active' : ''}" data-tab="diff">${escapeHtml(c('diff'))}</button>
          <button class="tab-btn ${activeTab === 'plan' ? 'active' : ''}" data-tab="plan">${escapeHtml(c('plan'))}</button>
        </div>

        <div class="editor-tab-content card">${renderTabContent()}</div>

        <div class="editor-actions">
          <button class="button-secondary" id="btn-insert-media">${escapeHtml(c('media'))}</button>
          <button class="button-secondary" id="btn-diff">${escapeHtml(c('previewDiff'))}</button>
          <button class="button-secondary" id="btn-plan">${escapeHtml(c('dryRun'))}</button>
          <button class="button-secondary" id="btn-create-pr" ${readiness.liveWritesEnabled === true ? '' : 'disabled'} title="${readiness.liveWritesEnabled === true ? 'Ready' : 'Create Review PR unavailable: LIVE_WRITES_ENABLED=false'}">${escapeHtml(c('createPr'))}</button>
          <button class="button-primary" id="btn-publish-test" ${isTestDirectPublishEnabled ? '' : 'disabled'} title="${escapeHtml(testPublishDisabledReason || 'Ready')}">${escapeHtml(c('publishTest'))}</button>
        </div>

        ${readiness.liveWritesEnabled === true ? '' : `<p class="help-text">${escapeHtml(c('prUnavailable'))}</p>`}
        ${!isTestDirectPublishEnabled ? `<p class="help-text">${escapeHtml(c('publishUnavailable'))}: ${escapeHtml(testPublishDisabledReason)}</p>` : ''}
        ${loadingState ? `<div class="info-text">${escapeHtml(isZh() ? '处理中...' : 'Working...')}</div>` : ''}
        ${actionResultHtml}
      </div>
    `;

    bindEvents();
    if (!autoLoadAttempted && post.slug && !post.body && !loadingState) {
      autoLoadAttempted = true;
      setTimeout(() => loadExistingSource(), 0);
    }
  }

  function renderTabContent() {
    if (activeTab === 'diff') return diffHtml || `<p class="info-text">${escapeHtml(c('emptyDiff'))}</p>`;
    if (activeTab === 'plan') return planHtml || `<p class="info-text">${escapeHtml(c('emptyPlan'))}</p>`;

    return `
      <div class="editor-fields-grid">
        <label><span>${escapeHtml(c('titleField'))}</span><input type="text" id="edit-title" value="${escapeHtml(post.title)}" placeholder="Hello World" /></label>
        <label><span>${escapeHtml(c('slug'))}</span><input type="text" id="edit-slug" value="${escapeHtml(post.slug)}" placeholder="hello-world" /></label>
        <label><span>${escapeHtml(c('category'))}</span><input type="text" id="edit-category" value="${escapeHtml(post.category)}" placeholder="Life" /></label>
        <label><span>${escapeHtml(c('tags'))}</span><input type="text" id="edit-tags" value="${escapeHtml(post.tags)}" placeholder="personal, welcome" /></label>
        <label class="field-span-2"><span>${escapeHtml(c('sourcePath'))}</span><input type="text" id="edit-file-path" value="${escapeHtml(post.filePath || '')}" placeholder="source/_posts/2026-01-01-example.md" /></label>
        <div class="field-span-2 media-shortcut-bar" aria-label="${escapeHtml(c('mediaShortcuts'))}">
          <span>${escapeHtml(c('mediaShortcuts'))}</span>
          ${MEDIA_SNIPPETS.map((item) => `<button type="button" class="button-small button-secondary btn-media-snippet" data-media-snippet="${escapeHtml(item.id)}">${escapeHtml(isZh() ? item.zh : item.en)}</button>`).join('')}
        </div>
        <div class="field-span-2 markdown-editor-shell">
          <label class="markdown-input-pane"><span>${escapeHtml(c('body'))}</span><div id="vditor-editor" class="vditor-host"></div><textarea id="edit-body" rows="22" spellcheck="false" placeholder="${escapeHtml(c('vditorPlaceholder'))}">${escapeHtml(post.body)}</textarea></label>
          <div class="markdown-editor-status">${renderMarkdownStats(post.body)}</div>
        </div>
      </div>
    `;
  }

  function bindEvents() {
    container.querySelectorAll('.tab-btn').forEach((btn) => {
      btn.addEventListener('click', () => {
        syncFromForm();
        activeTab = btn.getAttribute('data-tab') || 'edit';
        draw();
      });
    });
    container.querySelector('#btn-template-first')?.addEventListener('click', () => useTemplate('first-test'));
    container.querySelector('#btn-template-empty')?.addEventListener('click', () => useTemplate('empty'));
    container.querySelector('#btn-load-source')?.addEventListener('click', () => {
      syncFromForm();
      loadExistingSource();
    });
    container.querySelector('#btn-diff')?.addEventListener('click', fetchDiffPreview);
    container.querySelector('#btn-plan')?.addEventListener('click', fetchPublishPlan);
    container.querySelector('#btn-create-pr')?.addEventListener('click', handleCreatePR);
    container.querySelector('#btn-publish-test')?.addEventListener('click', handlePublishToTest);
    container.querySelector('#btn-insert-media')?.addEventListener('click', () => {
      insertMarkdownSnippet('\n![media description](media/example-image.png)\n');
      showToast(c('insertMedia'), 'info');
    });
    container.querySelectorAll('[data-media-snippet]').forEach((button) => {
      button.addEventListener('click', () => {
        const item = MEDIA_SNIPPETS.find((candidate) => candidate.id === button.getAttribute('data-media-snippet'));
        if (!item) return;
        insertMarkdownSnippet(item.snippet);
        showToast(c('insertMedia'), 'info');
      });
    });
    const bodyInput = container.querySelector('#edit-body');
    bodyInput?.addEventListener('input', () => {
      post.body = bodyInput.value;
      updateStatus();
    });
    mountVditor();
  }

  function mountVditor() {
    const host = container.querySelector('#vditor-editor');
    const textarea = container.querySelector('#edit-body');
    if (!host || !textarea || host.dataset.ready === 'true') return;
    ensureVditorAssets().then((Vditor) => {
      if (!Vditor || !container.contains(host)) return;
      textarea.style.display = 'none';
      host.dataset.ready = 'true';
      const lang = getLanguage() === 'zh-CN' ? 'zh_CN' : 'en_US';
      const editor = new Vditor(host, {
        value: post.body || '',
        height: 620,
        mode: 'ir',
        lang,
        cache: { enable: false },
        placeholder: c('vditorPlaceholder'),
        toolbar: ['emoji', 'headings', 'bold', 'italic', 'strike', '|', 'list', 'ordered-list', 'check', '|', 'quote', 'line', 'code', 'inline-code', '|', 'upload', 'link', 'table', '|', 'undo', 'redo', 'preview', 'fullscreen'],
        input(value) {
          post.body = value;
          textarea.value = value;
          updateStatus();
        },
        upload: {
          accept: 'image/*,audio/*,video/*,.pdf,.doc,.docx,.ppt,.pptx,.xls,.xlsx,.zip',
          handler(files) {
            const snippets = Array.from(files || []).map((file) => buildMediaSnippet(file.name, file.type)).join('\n');
            editor.insertValue(`\n${snippets}\n`);
            return null;
          }
        }
      });
      host._xhaloVditor = editor;
    }).catch((err) => {
      showToast(`Vditor failed to load; textarea fallback is active: ${err.message}`, 'warning');
    });
  }

  function updateStatus() {
    const status = container.querySelector('.markdown-editor-status');
    if (status) status.innerHTML = renderMarkdownStats(post.body);
  }

  function insertMarkdownSnippet(snippet) {
    const host = container.querySelector('#vditor-editor');
    if (host?._xhaloVditor) {
      host._xhaloVditor.insertValue(snippet);
      post.body = host._xhaloVditor.getValue();
      updateStatus();
      return;
    }
    const textarea = container.querySelector('#edit-body');
    if (!textarea) return;
    const start = textarea.selectionStart || 0;
    textarea.value = `${textarea.value.slice(0, start)}${snippet}${textarea.value.slice(start)}`;
    post.body = textarea.value;
    updateStatus();
  }

  draw();
}

function normalizePost(post) {
  return {
    ...EMPTY_POST,
    ...post,
    tags: Array.isArray(post?.tags) ? post.tags.join(', ') : (post?.tags || ''),
    filePath: post?.filePath || post?.path || post?.targetPath || ''
  };
}

function buildMediaSnippet(filename, contentType = '') {
  const safeName = encodeURI(filename || 'media-file');
  if (contentType.startsWith('audio/')) return `<audio controls src="media/${safeName}"></audio>`;
  if (contentType.startsWith('video/')) return `<video controls src="media/${safeName}"></video>`;
  if (contentType.startsWith('image/')) return `![${filename}](media/${safeName})`;
  return `[${filename}](media/${safeName})`;
}

function renderMarkdownStats(markdown) {
  const text = String(markdown || '');
  const lines = text ? text.split(/\r?\n/).length : 0;
  const chars = text.length;
  const words = text.trim() ? text.trim().split(/\s+/).length : 0;
  return escapeHtml(interpolate(c('stats'), { lines, chars, words }));
}
