import {
  buildProviderReadinessSnapshot,
  buildDraftMarkdownDocument,
  buildDraftTaskPrototype,
  buildGitHubWritePlan,
  buildModerationPreview,
  buildModerationTaskPrototype,
  buildPublishNotificationPreview,
  buildPublishNotificationTaskPrototype,
  buildPullRequestPreview,
  buildQueueTaskEnvelope,
  buildR2UploadPreview,
  buildR2UploadTaskPrototype,
  buildR2UploadWritePlan,
  defaultDraftTemplate,
  defaultModerationTemplate,
  defaultPublishNotificationTemplate,
  defaultR2UploadTemplate,
  createFallbackPosts,
  createFallbackTasks,
  createJsonResponse,
  getScaffoldMetadata,
  nowIso
} from '../../../packages/core/src/index.js';

function getGitHubFetch(env) {
  return env.GITHUB_FETCH || fetch;
}

function getGitHubRepository(env) {
  return {
    owner: env.GITHUB_OWNER || 'example',
    repo: env.GITHUB_REPO || 'xhalo-blog',
    baseBranch: env.GITHUB_BRANCH || 'main'
  };
}

function encodeBase64Utf8(input) {
  const bytes = new TextEncoder().encode(input);
  let binary = '';
  for (const byte of bytes) binary += String.fromCharCode(byte);
  if (typeof btoa === 'function') return btoa(binary);
  return Buffer.from(bytes).toString('base64');
}

function decodeBase64ToBytes(input) {
  const normalized = String(input || '').replace(/\s+/g, '');
  if (typeof atob === 'function') {
    const binary = atob(normalized);
    const bytes = new Uint8Array(binary.length);
    for (let index = 0; index < binary.length; index += 1) {
      bytes[index] = binary.charCodeAt(index);
    }
    return bytes;
  }
  return Uint8Array.from(Buffer.from(normalized, 'base64'));
}

function buildR2UploadBody(input = {}) {
  const encoding = String(input.encoding || defaultR2UploadTemplate.defaults.encoding).trim().toLowerCase() === 'base64'
    ? 'base64'
    : defaultR2UploadTemplate.defaults.encoding;
  const cacheControl = String(input.cacheControl || defaultR2UploadTemplate.defaults.cacheControl).trim()
    || defaultR2UploadTemplate.defaults.cacheControl;
  const rawContent = input.content == null || String(input.content).length === 0
    ? `Prototype asset written at ${nowIso()}\n`
    : String(input.content);
  const body = encoding === 'base64'
    ? decodeBase64ToBytes(rawContent)
    : new TextEncoder().encode(rawContent);

  return {
    body,
    encoding,
    cacheControl,
    byteLength: body.byteLength
  };
}

async function githubApiRequest(env, path, init = {}) {
  const headers = new Headers(init.headers || {});
  headers.set('accept', 'application/vnd.github+json');
  headers.set('x-github-api-version', '2022-11-28');

  if (env.GITHUB_TOKEN) {
    headers.set('authorization', `Bearer ${env.GITHUB_TOKEN}`);
  }

  const response = await getGitHubFetch(env)(`https://api.github.com${path}`, {
    ...init,
    headers
  });

  if (!response.ok) {
    const text = await response.text();
    const error = new Error(`GitHub API ${response.status}: ${text}`);
    error.status = response.status;
    throw error;
  }

  if (response.status === 204) return null;
  return response.json();
}

async function getBranchHeadSha(env, branchName) {
  const { owner, repo } = getGitHubRepository(env);
  const result = await githubApiRequest(env, `/repos/${owner}/${repo}/git/ref/heads/${encodeURIComponent(branchName)}`);
  return result.object.sha;
}

async function createBranchIfMissing(env, branchName, baseSha) {
  const { owner, repo } = getGitHubRepository(env);

  try {
    await githubApiRequest(env, `/repos/${owner}/${repo}/git/refs`, {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify({
        ref: `refs/heads/${branchName}`,
        sha: baseSha
      })
    });
    return { created: true };
  } catch (error) {
    if (error.status === 422) return { created: false };
    throw error;
  }
}

async function createDraftFileCommit(env, filePath, branchName, content, commitMessage) {
  const { owner, repo } = getGitHubRepository(env);
  return githubApiRequest(env, `/repos/${owner}/${repo}/contents/${filePath}`, {
    method: 'PUT',
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify({
      message: commitMessage,
      content: encodeBase64Utf8(content),
      branch: branchName
    })
  });
}

async function createPullRequest(env, preview) {
  const { owner, repo } = getGitHubRepository(env);
  return githubApiRequest(env, `/repos/${owner}/${repo}/pulls`, {
    method: 'POST',
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify({
      title: preview.pullRequestTitle,
      head: preview.branchName,
      base: preview.baseBranch,
      body: `Generated by xhalo-blog live draft publish prototype for \`${preview.filePath}\`.`
    })
  });
}

async function selectRows(env, sql) {
  if (!env.DB || typeof env.DB.prepare !== 'function') return null;
  const result = await env.DB.prepare(sql).all();
  return Array.isArray(result?.results) ? result.results : [];
}

async function insertTaskRecord(env, task) {
  if (!env.DB || typeof env.DB.prepare !== 'function') return false;

  await env.DB.prepare(
    'INSERT INTO tasks (id, type, status, payload, error, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?)'
  ).bind(
    task.id,
    task.type,
    task.status,
    JSON.stringify(task.payload),
    null,
    task.created_at,
    task.updated_at
  ).run();

  return true;
}

async function upsertPostIndexRecord(env, record) {
  if (!env.DB || typeof env.DB.prepare !== 'function') return false;

  await env.DB.prepare(
    `INSERT OR REPLACE INTO posts_index
    (id, slug, title, path, status, created_at, updated_at, published_at, github_branch, github_pr_url)
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`
  ).bind(
    record.id,
    record.slug,
    record.title,
    record.path,
    record.status,
    record.created_at,
    record.updated_at,
    record.published_at || null,
    record.github_branch || null,
    record.github_pr_url || null
  ).run();

  return true;
}

async function putAssetObject(env, preview, uploadBody) {
  if (!env.ASSETS || typeof env.ASSETS.put !== 'function') return null;

  return env.ASSETS.put(preview.objectKey, uploadBody.body, {
    httpMetadata: {
      contentType: preview.contentType,
      cacheControl: uploadBody.cacheControl
    },
    customMetadata: {
      scope: preview.scope,
      filename: preview.filename,
      ...(preview.postSlug ? { postSlug: preview.postSlug } : {})
    }
  });
}

export default {
  async fetch(request, env) {
    const url = new URL(request.url);

    if (url.pathname === '/api/health') {
      return createJsonResponse({ ok: true, service: 'xhalo-blog-api', stage: '3-prototype', mode: 'scaffold' });
    }

    if (url.pathname === '/api/readiness') {
      return createJsonResponse(buildProviderReadinessSnapshot(env));
    }

    if (url.pathname === '/api/scaffold') {
      return createJsonResponse(getScaffoldMetadata());
    }

    if (url.pathname === '/api/posts') {
      const items = await selectRows(
        env,
        'SELECT id, slug, title, path, status, created_at, updated_at, published_at, github_branch, github_pr_url FROM posts_index ORDER BY COALESCE(updated_at, created_at) DESC LIMIT 10'
      );

      return createJsonResponse({
        items: items ?? createFallbackPosts(),
        backend: items ? 'd1' : 'fallback',
        source_of_truth: 'git',
        note: items ? 'Read-only posts_index prototype.' : 'D1 posts_index integration pending; showing fallback examples.'
      });
    }

    if (url.pathname === '/api/tasks') {
      const items = await selectRows(
        env,
        'SELECT id, type, status, payload, error, created_at, updated_at FROM tasks ORDER BY updated_at DESC LIMIT 10'
      );

      return createJsonResponse({
        items: items ?? createFallbackTasks(),
        backend: items ? 'd1' : 'fallback',
        note: items ? 'Read-only tasks prototype.' : 'D1 task status integration pending; showing fallback examples.'
      });
    }

    if (url.pathname === '/api/drafts/template') {
      return createJsonResponse({
        template: defaultDraftTemplate,
        note: 'Stage 3 draft metadata prototype. No real GitHub write happens here.'
      });
    }

    if (url.pathname === '/api/drafts/preview' && request.method === 'POST') {
      const input = await request.json();
      const preview = buildPullRequestPreview(input, {
        repoOwner: env.GITHUB_OWNER || 'example',
        repoName: env.GITHUB_REPO || 'xhalo-blog',
        baseBranch: env.GITHUB_BRANCH || 'main'
      });

      return createJsonResponse({
        preview,
        note: 'Stage 3 draft and PR preview only. No branch or PR has been created.'
      });
    }

    if (url.pathname === '/api/drafts/tasks' && request.method === 'POST') {
      if (!env.TASK_QUEUE) return createJsonResponse({ error: 'TASK_QUEUE is not bound' }, { status: 500 });

      const input = await request.json();
      const prototype = buildDraftTaskPrototype(input, {
        repoOwner: env.GITHUB_OWNER || 'example',
        repoName: env.GITHUB_REPO || 'xhalo-blog',
        baseBranch: env.GITHUB_BRANCH || 'main',
        stage: '3-prototype'
      });

      await env.TASK_QUEUE.send(prototype.queuedTask);
      const persisted = await insertTaskRecord(env, prototype.taskRecord);

      return createJsonResponse({
        queued: true,
        persisted,
        task_id: prototype.taskRecord.id,
        task_type: prototype.taskRecord.type,
        preview: prototype.preview,
        note: 'Dry-run draft task queued. No GitHub branch or PR has been created.'
      });
    }

    if (url.pathname === '/api/drafts/github-plan' && request.method === 'POST') {
      const input = await request.json();
      const plan = buildGitHubWritePlan(input, {
        repoOwner: env.GITHUB_OWNER || 'example',
        repoName: env.GITHUB_REPO || 'xhalo-blog',
        baseBranch: env.GITHUB_BRANCH || 'main'
      });

      return createJsonResponse({
        preview: buildPullRequestPreview(input, {
          repoOwner: env.GITHUB_OWNER || 'example',
          repoName: env.GITHUB_REPO || 'xhalo-blog',
          baseBranch: env.GITHUB_BRANCH || 'main'
        }),
        plan,
        note: 'Dry-run GitHub operation plan only. No branch, commit, or PR has been created.'
      });
    }

    if (url.pathname === '/api/drafts/publish' && request.method === 'POST') {
      const input = await request.json();
      const mode = input.mode === 'live' ? 'live' : 'dry-run';
      const repository = getGitHubRepository(env);
      const preview = buildPullRequestPreview(input, {
        repoOwner: repository.owner,
        repoName: repository.repo,
        baseBranch: repository.baseBranch
      });
      const plan = buildGitHubWritePlan(input, {
        repoOwner: repository.owner,
        repoName: repository.repo,
        baseBranch: repository.baseBranch
      });

      if (mode !== 'live') {
        return createJsonResponse({
          mode,
          preview,
          plan,
          note: 'Dry-run draft publish only. No branch, commit, or PR has been created.'
        });
      }

      if (!env.GITHUB_TOKEN) {
        return createJsonResponse({
          error: 'GITHUB_TOKEN is required for the live draft publish prototype.',
          mode
        }, { status: 503 });
      }

      const markdown = buildDraftMarkdownDocument(input);
      const baseSha = await getBranchHeadSha(env, preview.baseBranch);
      const branchResult = await createBranchIfMissing(env, preview.branchName, baseSha);
      const commitResult = await createDraftFileCommit(
        env,
        preview.filePath,
        preview.branchName,
        markdown,
        preview.commitMessage
      );
      const pullRequest = await createPullRequest(env, preview);
      const persisted = await upsertPostIndexRecord(env, {
        id: preview.draft.slug,
        slug: preview.draft.slug,
        title: preview.draft.title || preview.draft.slug,
        path: preview.filePath,
        status: 'draft',
        created_at: nowIso(),
        updated_at: nowIso(),
        github_branch: preview.branchName,
        github_pr_url: pullRequest.html_url
      });

      return createJsonResponse({
        mode,
        preview,
        plan,
        branch_created: branchResult.created,
        content_path: commitResult?.content?.path || preview.filePath,
        commit_sha: commitResult?.commit?.sha || null,
        pull_request: {
          number: pullRequest.number,
          url: pullRequest.html_url
        },
        persisted
      });
    }

    if (url.pathname === '/api/assets/r2-template') {
      return createJsonResponse({
        template: defaultR2UploadTemplate,
        note: 'Stage 3 R2 upload prototype. No real signed upload or bucket write happens here.'
      });
    }

    if (url.pathname === '/api/assets/r2-preview' && request.method === 'POST') {
      const input = await request.json();
      const preview = buildR2UploadPreview(input, {
        bucketBinding: 'ASSETS',
        bucketName: 'xhalo-blog-assets',
        publicBaseUrl: env.ASSETS_PUBLIC_BASE_URL || defaultR2UploadTemplate.publicBaseUrl
      });

      return createJsonResponse({
        preview,
        note: 'Stage 3 R2 upload preview only. No object has been written.'
      });
    }

    if (url.pathname === '/api/assets/r2-upload' && request.method === 'POST') {
      const input = await request.json();
      const mode = input.mode === 'live' ? 'live' : 'dry-run';
      const preview = buildR2UploadPreview(input, {
        bucketBinding: 'ASSETS',
        bucketName: 'xhalo-blog-assets',
        publicBaseUrl: env.ASSETS_PUBLIC_BASE_URL || defaultR2UploadTemplate.publicBaseUrl
      });
      const plan = buildR2UploadWritePlan(input, {
        bucketBinding: 'ASSETS',
        bucketName: 'xhalo-blog-assets',
        publicBaseUrl: env.ASSETS_PUBLIC_BASE_URL || defaultR2UploadTemplate.publicBaseUrl
      });

      if (mode !== 'live') {
        return createJsonResponse({
          mode,
          preview,
          plan,
          note: 'Dry-run R2 upload only. No object has been written.'
        });
      }

      if (!env.ASSETS || typeof env.ASSETS.put !== 'function') {
        return createJsonResponse({
          error: 'ASSETS binding is required for the live R2 upload prototype.',
          mode
        }, { status: 503 });
      }

      if (!env.ASSETS_PUBLIC_BASE_URL) {
        return createJsonResponse({
          error: 'ASSETS_PUBLIC_BASE_URL is required for the live R2 upload prototype.',
          mode
        }, { status: 503 });
      }

      const uploadBody = buildR2UploadBody(input);
      if (uploadBody.byteLength > 256 * 1024) {
        return createJsonResponse({
          error: 'Prototype uploads are limited to 256 KiB.',
          mode,
          uploaded_bytes: uploadBody.byteLength
        }, { status: 413 });
      }

      const object = await putAssetObject(env, preview, uploadBody);
      const recordedAt = nowIso();
      const persisted = await insertTaskRecord(env, {
        id: crypto.randomUUID(),
        type: 'r2_upload_live',
        status: 'completed',
        payload: {
          mode,
          preview,
          encoding: uploadBody.encoding,
          cacheControl: uploadBody.cacheControl,
          uploaded_bytes: uploadBody.byteLength
        },
        created_at: recordedAt,
        updated_at: recordedAt
      });

      return createJsonResponse({
        mode,
        preview,
        plan,
        uploaded_bytes: uploadBody.byteLength,
        etag: object?.etag || null,
        version: object?.version || null,
        persisted
      });
    }

    if (url.pathname === '/api/assets/r2-tasks' && request.method === 'POST') {
      if (!env.TASK_QUEUE) return createJsonResponse({ error: 'TASK_QUEUE is not bound' }, { status: 500 });

      const input = await request.json();
      const prototype = buildR2UploadTaskPrototype(input, {
        bucketBinding: 'ASSETS',
        bucketName: 'xhalo-blog-assets',
        publicBaseUrl: env.ASSETS_PUBLIC_BASE_URL || defaultR2UploadTemplate.publicBaseUrl,
        stage: '3-prototype'
      });

      await env.TASK_QUEUE.send(prototype.queuedTask);
      const persisted = await insertTaskRecord(env, prototype.taskRecord);

      return createJsonResponse({
        queued: true,
        persisted,
        task_id: prototype.taskRecord.id,
        task_type: prototype.taskRecord.type,
        preview: prototype.preview,
        note: 'Dry-run R2 upload task queued. No object has been written.'
      });
    }

    if (url.pathname === '/api/publish/notifications/template') {
      return createJsonResponse({
        template: defaultPublishNotificationTemplate,
        note: 'Stage 3 publish notification prototype. No real downstream notification is sent here.'
      });
    }

    if (url.pathname === '/api/publish/notifications/preview' && request.method === 'POST') {
      const input = await request.json();
      const preview = buildPublishNotificationPreview(input, {
        queueBinding: 'TASK_QUEUE'
      });

      return createJsonResponse({
        preview,
        note: 'Stage 3 publish notification preview only. No downstream notification has been sent.'
      });
    }

    if (url.pathname === '/api/publish/notifications/tasks' && request.method === 'POST') {
      if (!env.TASK_QUEUE) return createJsonResponse({ error: 'TASK_QUEUE is not bound' }, { status: 500 });

      const input = await request.json();
      const prototype = buildPublishNotificationTaskPrototype(input, {
        queueBinding: 'TASK_QUEUE',
        stage: '3-prototype'
      });

      await env.TASK_QUEUE.send(prototype.queuedTask);
      const persisted = await insertTaskRecord(env, prototype.taskRecord);

      return createJsonResponse({
        queued: true,
        persisted,
        task_id: prototype.taskRecord.id,
        task_type: prototype.taskRecord.type,
        preview: prototype.preview,
        note: 'Dry-run publish notification task queued. No downstream notification has been sent.'
      });
    }

    if (url.pathname === '/api/moderation/template') {
      return createJsonResponse({
        template: defaultModerationTemplate,
        note: 'Stage 3 moderation prototype. No real comment provider write happens here.'
      });
    }

    if (url.pathname === '/api/moderation/preview' && request.method === 'POST') {
      const input = await request.json();
      const preview = buildModerationPreview(input, {
        queueBinding: 'TASK_QUEUE'
      });

      return createJsonResponse({
        preview,
        note: 'Stage 3 moderation preview only. No real comment has been updated.'
      });
    }

    if (url.pathname === '/api/moderation/tasks' && request.method === 'POST') {
      if (!env.TASK_QUEUE) return createJsonResponse({ error: 'TASK_QUEUE is not bound' }, { status: 500 });

      const input = await request.json();
      const prototype = buildModerationTaskPrototype(input, {
        queueBinding: 'TASK_QUEUE',
        stage: '3-prototype'
      });

      await env.TASK_QUEUE.send(prototype.queuedTask);
      const persisted = await insertTaskRecord(env, prototype.taskRecord);

      return createJsonResponse({
        queued: true,
        persisted,
        task_id: prototype.taskRecord.id,
        task_type: prototype.taskRecord.type,
        preview: prototype.preview,
        note: 'Dry-run moderation task queued. No real comment has been updated.'
      });
    }

    if (url.pathname === '/api/tasks/example' && request.method === 'POST') {
      if (!env.TASK_QUEUE) return createJsonResponse({ error: 'TASK_QUEUE is not bound' }, { status: 500 });

      const queuedTask = buildQueueTaskEnvelope({
        type: 'example',
        stage: '3-prototype',
        created_at: nowIso(),
        idempotency_key: crypto.randomUUID()
      });

      const taskRecord = {
        id: queuedTask.idempotency_key || crypto.randomUUID(),
        type: queuedTask.type,
        status: 'queued',
        payload: queuedTask,
        created_at: queuedTask.created_at,
        updated_at: queuedTask.created_at
      };

      await env.TASK_QUEUE.send(queuedTask);
      const persisted = await insertTaskRecord(env, taskRecord);

      return createJsonResponse({
        queued: true,
        persisted,
        task_id: taskRecord.id,
        task_type: taskRecord.type,
        queue_binding: 'TASK_QUEUE'
      });
    }

    return createJsonResponse({ error: 'Not found' }, { status: 404 });
  }
};
